### ISSUE TITLE
error on ubuntu

### ISSUE THREAD

**Issue by yopiucing** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#13]
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/seed/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/seed/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/root/seed/.venv/lib/python3.8/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy, parse_proxy_str
  File "/root/seed/.venv/lib/python3.8/site-packages/better_proxy/proxy.py", line 16, in <module>
    class ParsedProxy(TypedDict):
  File "/root/seed/.venv/lib/python3.8/site-packages/better_proxy/proxy.py", line 19, in ParsedProxy
    protocol: Protocol | None
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

**Comment by vanhbakaa** [comment]
Use python 3.10+
