### ISSUE TITLE
Unknown error: Cannot serialize non-str key None

### ISSUE THREAD

**Issue by qienzdork** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#23]
Traceback (most recent call last):
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/bot/core/tapper.py", line 457, in run
    not_new_user = await self.check_new_user(http_client)
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/bot/core/tapper.py", line 424, in check_new_user
    response = await http_client.get(new_user_api)
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.10/site-packages/aiocfscrape/__init__.py", line 79, in _request
    resp = await super()._request(method, url, *args, **kwargs)
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.10/site-packages/aiohttp/client.py", line 603, in _request
    resp = await req.send(conn)
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 713, in send
    await writer.write_headers(status_line, self.headers)
  File "/root/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.10/site-packages/aiohttp/http_writer.py", line 129, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
2024-09-30 01:58:42 | ERROR    | 599 - qienx | Unknown error: Cannot serialize non-str key None

**Comment by vanhbakaa** [comment]
Restart the bot if you still get this problem please tell me
