### ISSUE TITLE
TypeError: Object of type coroutine is not JSON serializable

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#26]
```
Traceback (most recent call last):
  File "/home/name/bots/Seed-App-Mine-Seed-BOT-Telegram/bot/core/tapper.py", line 584, in run
    await self.sell_worm(worm['id'], price_to_sell, worm['type'], http_client)
  File "/home/name/bots/Seed-App-Mine-Seed-BOT-Telegram/bot/core/tapper.py", line 376, in sell_worm
    response = await http_client.post(api_sell, json=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/aiocfscrape/__init__.py", line 79, in _request
    resp = await super()._request(method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/aiohttp/client.py", line 434, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/aiohttp/payload.py", line 396, in __init__
    dumps(value).encode(encoding),
    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable

```

**Comment by Mr-Mk7** [comment]
having the same problem if you find any solution please let me know

**Comment by vanhbakaa** [comment]
fixed
