### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Nord1cWarr1or** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#49]
```
2024-11-09 23:33:51 | INFO     | 75 - Y | Doesn't have user agent, Creating...
Traceback (most recent call last):
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/main.py", line 13, in <module>
asyncio.run(main())
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/main.py", line 8, in main
await process()
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/launcher.py", line 144, in process
await run_tasks(tg_clients=tg_clients)
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/launcher.py", line 156, in run_tasks
tasks = [
^
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/launcher.py", line 161, in <listcomp>
ua=await get_user_agent(tg_client.name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/launcher.py", line 78, in get_user_agent
async with AIOFile('user_agents.json', 'w') as file:
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.11/site-packages/aiofile/aio.py", line 197, in close
await self.fdsync()
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.11/site-packages/aiofile/aio.py", line 295, in fdsync
return await self.__context.fdsync(self.fileno())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/tgbots/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.11/site-packages/caio/asyncio_base.py", line 47, in submit
if self.context.submit(op) != 1:
^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The AIO context specified by ctx_id is invalid. nr is less than 0. The iocb at *iocbpp[0] is not properly initialized, the operation specified is invalid for the file descriptor in the iocb, or the value in the aio_reqprio field is invalid. [EINVAL]
```

**Comment by Nord1cWarr1or** [comment]
@vanhbakaa not fixed
