### ISSUE TITLE
All installed, getting errors

### ISSUE THREAD

**Issue by ifilinv** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#5]
`Starting the bot...
Traceback (most recent call last):
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/bot/core/tapper.py", line 8, in <module>
    from aiocfscrape import CloudflareScraper
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Scripts/Seed-App-Mine-Seed-BOT-Telegram/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
`

**Comment by vanhbakaa** [comment]
use python 3.10-3.11.5
