### ISSUE TITLE
hi, please help me with this problem

### ISSUE THREAD

**Issue by Veterse** [vanhbakaa/Seed-App-Mine-Seed-BOT-Telegram#53]
it doesn't matter if I use a proxy or not, it's still the same error
Traceback (most recent call last):
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\main.py", line 8, in main
    await process()
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\bot\utils\launcher.py", line 182, in process
    await run_tasks(tg_clients=tg_clients)
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\bot\utils\launcher.py", line 191, in run_tasks
    tasks = [
            ^
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\bot\utils\launcher.py", line 195, in <listcomp>
    proxy=await get_proxy(tg_client.name),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Games\Seed-App-Mine-Seed-BOT-Telegram\bot\utils\launcher.py", line 105, in get_proxy
    async with AIOFile('proxy.json', 'r') as file:
  File "E:\Games\Seed-App-Mine-Seed-BOT-Telegram\.venv\Lib\site-packages\aiofile\aio.py", line 211, in __aenter__
    await self.open()
  File "E:\Games\Seed-App-Mine-Seed-BOT-Telegram\.venv\Lib\site-packages\aiofile\aio.py", line 182, in open
    self._file_obj = await self.__open_result
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'proxy.json'

**Comment by vanhbakaa** [comment]
reiinstall
